### PR TITLE
Publish Conda workflow file

### PR DESCRIPTION
**Pull request by bcc2761**
requires addition of GitHub Secret to work- shared via restricted Google doc

### CODE REVIEW

**Comment by bcc2761** [comment]
To test this, can copy added file to a fork and add a GitHub Secret in fork repo. Currently set to trigger upon 'push', but can be edited to trigger upon other events as well. Keep in mind that if there is a current intakebuilder package of the same name and version number on noaa-gfdl anaconda channel, it will remove that package without uploading a new one. Thus, either the version number needs to be changed, or this workflow would need to be triggered again.

**Comment by bcc2761** [comment]
Here is an example: https://github.com/NOAA-GFDL/fre-cli/actions/runs/7790006016/job/21242885023#step:4:666

I'm not quite sure what causes this behavior. When I first encountered it I thought it would act the same way as if done manually; i.e. it prints an error regarding the conflict about the same package name and version and fails the upload. For some reason though it removes the current as well

**Comment by aradhakrishnanGFDL** [comment]
> @aradhakrishnanGFDL Here is an example: https://github.com/NOAA-GFDL/fre-cli/actions/runs/7790006016/job/21242885023#step:4:666
> 
> I'm not quite sure what causes this behavior. When I first encountered it I thought it would act the same way as if done manually; i.e. it prints an error regarding the conflict about the same package name and version and fails the upload. For some reason though it removes the current as well

@bcc2761 Doesn't the log you pointed actually publish the same version after the warning and the error message? To me, it sounds like it gives a warning about the version. If it's the same, it is overridden (remove existing one in the channel, publish one from the workflow) by the current build, associating the same version. Let me know how to confirm this. 

Warning:  Distribution "noarch/fre-cli-0.1.0-py_0.tar.bz2" already exists. Removing.
Error:  ("release version='0.1.0' does not exist", 40

https://github.com/NOAA-GFDL/fre-cli/actions/runs/7790006016/job/21242885023#step:4:666

**Comment by aradhakrishnanGFDL** [comment]
copy of this PR is here https://github.com/aradhakrishnanGFDL/CatalogBuilder/pull/55. I will mark this present PR as draft and close both when it's complete

I have the branch in the same repository, and the test actions file running on pull request rather than a push to actually test and see what's going on. 

https://github.com/aradhakrishnanGFDL/CatalogBuilder/actions/runs/7935656794/job/21669273908?pr=55

**Pull request closed without merging**
