### PR TITLE
unified wrapper for cmip

### PR DESCRIPTION
**Pull request by aradhakrishnanGFDL**
This PR addresses #129. 

To test: Please test on a GFDL PP directory as well to make sure nothing broke there. Then, test the CMIP data using the following example or adapt to something else

./gen_intake_gfdl.py --config config-cmip.yaml

config-cmip.yaml is now in configs/ and has a test-case for CMIP. 

Expected csv and json 

JSON generated at: /home/a1r/github/CatalogBuilder/scripts/catalogcmip.json
CSV generated at: /home/a1r/github/CatalogBuilder/scripts/catalogcmip.csv

### CODE REVIEW

**Comment by aradhakrishnanGFDL** [comment]
import intake, intake_esm
col = "/home/a1r/github/CatalogBuilder/scripts/catalogcmip.json"
cat = intake.open_esm_datastore(col)

cat2 = cat.search(variable_id="tos",table_id="Oday")
cat2.df.grid_label.unique # you will see there are two grids for this field and table mapping
dset_dict = cat2.to_dataset_dict(cdf_kwargs={'chunks': {'time':5}, 'decode_times': False})

**Comment by aradhakrishnanGFDL** [comment]
Add: table_id, grid_label, version_id to the json.

Then it works.

source /net2/rlm/analysis-scripts/example/env/bin/activate

```
import intake, intake_esm
col = "/home/a1r/github/CatalogBuilder/scripts/catalogcmip-2.json"
cat = intake.open_esm_datastore(col)
cat2 = cat.search(variable_id="tos",table_id="Oday",grid_label="gn")
dset_dict = cat2.to_dataset_dict(cdf_kwargs={'chunks': {'time':5}, 'decode_times': False})
dset_dict.keys()
```
dict_keys(['GFDL-ESM4.abrupt-4xCO2.r1i1p1f1.Oday.v20180701.tos.gn', 'GFDL-ESM4.1pctCO2.r1i1p1f1.Oday.v20180701.tos.gn', 'GFDL-ESM4.historical.r1i1p1f1.Oday.v20190726.tos.gn', 'GFDL-ESM4.historical.r2i1p1f1.Oday.v20180701.tos.gn', 'GFDL-ESM4.esm-hist.r1i1p1f1.Oday.v20180701.tos.gn', 'GFDL-ESM4.historical.r3i1p1f1.Oday.v20180701.tos.gn', 'GFDL-ESM4.piControl.r1i1p1f1.Oday.v20180701.tos.gn'])

**Comment by aradhakrishnanGFDL** [comment]
if we remove version_id from agg columns, still works. 
```
col = "/home/a1r/github/CatalogBuilder/scripts/catalogcmip-3.json"

cat2 = cat.search(variable_id="tos",table_id="Oday",grid_label='gr')
dset_dict = cat2.to_dataset_dict(cdf_kwargs={'chunks': {'time':5}, 'decode_times': False})

```
--> The keys in the returned dictionary of datasets are constructed as follows:
	'source_id.experiment_id.member_id.table_id.grid_label'
█████████████████████████████████████████████████████████████| 100.00% [7/7 08:59<00:00]
`dset_dict.keys()`
dict_keys(['GFDL-ESM4.1pctCO2.r1i1p1f1.Oday.gr', 'GFDL-ESM4.abrupt-4xCO2.r1i1p1f1.Oday.gr', 'GFDL-ESM4.esm-hist.r1i1p1f1.Oday.gr', 'GFDL-ESM4.historical.r2i1p1f1.Oday.gr', 'GFDL-ESM4.historical.r1i1p1f1.Oday.gr', 'GFDL-ESM4.historical.r3i1p1f1.Oday.gr', 'GFDL-ESM4.piControl.r1i1p1f1.Oday.gr'])
>>> 

Ofcourse, Oday/tos has only one version.
What-if there are two versions?

`cat2 = cat.search(variable_id="dissocos",table_id="Omon",grid_label='gr')
`

**Comment by aradhakrishnanGFDL** [comment]
```
>>> cat2.df.groupby("variable_id")[["source_id","experiment_id","frequency","modeling_realm","member_id","table_id","grid_label","chunk_freq","version_id"]].nunique()
             source_id  experiment_id  frequency  modeling_realm  member_id  table_id  grid_label  chunk_freq  version_id
variable_id                                                                                                              
aragos               1              1          0               0          1         1           1           0           1
baccos               1              1          0               0          1         1           1           0           1
bfeos                1              1          0               0          1         1           1           0           1
bsios                1              1          0               0          1         1           1           0           1
calcos               1              1          0               0          1         1           1           0           1
...                ...            ...        ...             ...        ...       ...         ...         ...         ...
zmicro               1              1          0               0          1         1           1           0           1
zmicroos             1              1          0               0          1         1           1           0           1
zooc                 1              1          0               0          1         1           1           0           1
zoocos               1              1          0               0          1         1           1           0           1
zos                  1              1          0               0          1         1           1           0           1

[118 rows x 9 columns]
```

**Comment by aradhakrishnanGFDL** [comment]
examples and tests are documented here 
https://github.com/aradhakrishnanGFDL/canopy-cats/blob/main/notebooks/cmip_example.ipynb

sample catalogs are in the path described in the notebooks to find them locally at GFDL. There is also a copy of the catalogs in https://github.com/aradhakrishnanGFDL/canopy-cats/tree/main/catalogs/cmip-eg

**Review by ceblanton — APPROVED** [review]
This is great! I tested both the cmip and pp cases, and ran Ciheim's validator on both also. There was a duplicate grid_label in both csv headers that was harmless but I fixed.

**Pull request merged**
